spring.application.name=event-admin
spring.datasource.url=jdbc:postgresql://localhost:5432/eventadm
spring.datasource.username=eventadm
spring.datasource.password=eventadm
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
server.error.include-message=never
